// react_pro/src/components/MyBreadcrumb/MyBreadcrumb.js
import React, { Component, PropTypes } from 'react'
import './MyBreadcrumb.scss'
import { Breadcrumb } from 'antd'

class MyBreadcrumb extends Component {
  constructor (props) {
    super(props)
    this.state = {
      data: props.breadcrumb
    }
  }
  render () {
    return (
      <Breadcrumb>
        {this.state.data.map((item, index) => <Breadcrumb.Item key={index}>{item}</Breadcrumb.Item>)}
      </Breadcrumb>
    )
  }
}

MyBreadcrumb.propTypes = {
  breadcrumb: PropTypes.array
}

export default MyBreadcrumb

// vue/src/components/MyBreadcrumb/index.vue
<template>
  <el-breadcrumb separator="/" class="my-breadcrumb">
    <el-breadcrumb-item v-for="(item,index) in data" :key="index">{{item}}</el-breadcrumb-item>
  </el-breadcrumb>
</template>

<style>
  .my-breadcrumb {
    margin: 10px;
  }
</style>

<script>
  import { Breadcrumb, BreadcrumbItem } from 'element-ui'
  export default {
    components: {
      ElBreadcrumb: Breadcrumb,
      ElBreadcrumbItem: BreadcrumbItem
    },
    props: {
      data: Array
    }
  }
</script>
