// react_pro/src/components/MyCard/MyCard.js
import React, { Component, PropTypes } from 'react'
import './MyCard.scss'

class MyCard extends Component {
  render () {
    return (
      <div className="my-card">
        <div className="card-header">
          2012-12-12 12：12：12 （总经理审批）
          <span className="card-status">已驳回</span>
        </div>
        <div className="card-body">
          审批备注：这是审批人的备注
        </div>
      </div>
    )
  }
}

MyCard.propTypes = {
}

export default MyCard

// vue/src/components/MyCard/index.vue
<template>
	<div class="my-card">
		<div class="card-header">
			2012-12-12 12：12：12 （总经理审批）
			<span class="card-status">已驳回</span>
		</div>
		<div class="card-body">
			审批备注：这是审批人的备注
		</div>
	</div>
</template>

<style>
	.my-card {
		margin-top: 20px;
		border: 1px solid #ccc;
		color: #333;
		font-size: 14px;
		& .card-header {
			border-bottom: 1px solid #ccc;
			padding: 10px;
			& .card-status {
				float: right;
			}
		}
		& .card-body {
			padding: 10px;
		}
	}
</style>
